name: Deploy Vite React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        env : 
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_DATABASE_URL: ${{ secrets.VITE_FIREBASE_DATABASE_URL }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_SERVICE_ID_EMAIL_JS: ${{ secrets.VITE_SERVICE_ID_EMAIL_JS }}
          VITE_TEMPLATE_ID_EMAIL_JS: ${{ secrets.VITE_TEMPLATE_ID_EMAIL_JS }}
          VITE_USER_PUBLIC_KEY: ${{ secrets.VITE_USER_PUBLIC_KEY }}
        run : |
          echo "VITE_FIREBASE_API_KEY: $VITE_FIREBASE_API_KEY"
          echo "VITE_FIREBASE_AUTH_DOMAIN: $VITE_FIREBASE_AUTH_DOMAIN"
          echo "VITE_FIREBASE_PROJECT_ID: $VITE_FIREBASE_PROJECT_ID"
          echo "VITE_FIREBASE_DATABASE_URL: $VITE_FIREBASE_DATABASE_URL"
          echo "VITE_FIREBASE_STORAGE_BUCKET: $VITE_FIREBASE_STORAGE_BUCKET"
          echo "VITE_FIREBASE_MESSAGING_SENDER_ID: $VITE_FIREBASE_MESSAGING_SENDER_ID"
          echo "VITE_FIREBASE_APP_ID: $VITE_FIREBASE_APP_ID"
          echo "VITE_SERVICE_ID_EMAIL_JS: $VITE_SERVICE_ID_EMAIL_JS"
          echo "VITE_TEMPLATE_ID_EMAIL_JS: $VITE_TEMPLATE_ID_EMAIL_JS"
          echo "VITE_USER_PUBLIC_KEY: $VITE_USER_PUBLIC_KEY"
          npm run build
      - name: List files in dist folder
        run: ls -la ./dist  

  deploy:
      name: Deploy
      needs: build
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/main'
        
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./dist